# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getpairsOddXOut <- function(MatOut, MatIn, Yout, pch2) {
    .Call('_PairSeek_getpairsOddXOut', PACKAGE = 'PairSeek', MatOut, MatIn, Yout, pch2)
}

getpairsOddXOutRandomOrder <- function(MatOut, MatIn, Yout, pch2) {
    .Call('_PairSeek_getpairsOddXOutRandomOrder', PACKAGE = 'PairSeek', MatOut, MatIn, Yout, pch2)
}

RatioX <- function(MatIn, pch2) {
    .Call('_PairSeek_RatioX', PACKAGE = 'PairSeek', MatIn, pch2)
}

RankX <- function(MatIn, pch2) {
    .Call('_PairSeek_RankX', PACKAGE = 'PairSeek', MatIn, pch2)
}

